config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "articles", to: "articles#index"

  get "articles/new", to: "articles#new"

  get "articles/:id", to: "articles#show", as: :article

  post "articles", to: "articles#create"

  get "articles/:id/edit", to: "articles#edit", as: :edit_article

  patch "articles/:id", to: "articles#update"

  delete "articles/:id", to: "articles#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path

  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">wikinimous</a>
  <%= link_to "New Article", articles_new_path, class:'grey'%>
</nav>


<h1 class="new-article">Edit Article</h1>
<div class="container">
<%= simple_form_for(@article) do |f| %>
<div class="form-group">
  <%= f.input :title %>
  </div>
  <div class="form-group">
  <%= f.input :content %>
  </div>
  <%= f.submit %>
<% end %>
</div>

<%= link_to "Back", articles_path, class:'btn btn-primary' %>

app/views/articles/index.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">wikinimous</a>
  <%= link_to "New Article", articles_new_path, class:'grey' %>
</nav>


<div class="container">
<div class="article">
<% @articles.each do |article| %>
<h2> <%= link_to article.title, article_path(article) %> </h2>
<p><%= article.content %></p>
<% end %>
</div>

</div>

app/views/articles/new.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">wikinimous</a>
  <%= link_to "New Article", articles_new_path, class:'grey'%>
</nav>


<h1 class="new-article">New Article</h1>
<div class="container">
<%= simple_form_for(@article) do |f| %>
<div class="form-group">
  <%= f.input :title %>
  </div>
  <div class="form-group">
  <%= f.input :content %>
  </div>
  <%= f.submit %>
<% end %>
</div>

<%= link_to "Back", articles_path, class:'btn btn-primary' %>

app/views/articles/show.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">wikinimous</a>
   <%= link_to "New Article", articles_new_path, class:'grey' %>
</nav>

<div class="container">
<div class="article">
<%= link_to "Edit", edit_article_path %>
<%= link_to "Delete",
            article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<h2><%= @article.title %> </h2>

<p><%= @article.content %></p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>